CONTIKI_PROJECT = mqtt-udp-mote
all: $(CONTIKI_PROJECT)
CONTIKI = ../..

MODULES += os/net/app-layer/mqtt

#CFLAGS	+= -Wno-nonnull-compare -Wno-implicit-function-declaration

include $(CONTIKI)/Makefile.include
